#!/usr/bin/perl
# Copyright 2010 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

my $command = "mksysnum_tiny.sh ". join(' ', @ARGV);

# Nothing here right now, but let's follow the pattern of the others.

print <<EOF;
// $command
// MACHINE GENERATED BY THE ABOVE COMMAND; DO NOT EDIT

package syscall

const( )
EOF
